### ISSUE TITLE
I want to contact you

### ISSUE THREAD

**Issue by uwutizm** [BeepIsla/operation-missions#2]
Hi, I need to talk to you, do you have a discord? i have a question, sorry this is a problem not related to this project

**Comment by BeepIsla** [comment]
I don't give out my Discord.

If you don't have an issue related to this or any other **open** project don't ask.

**Comment by uwutizm** [comment]
@BeepIsla 

I just thought that it was possible to implement a **session killer** in CS:GO

**Comment by BeepIsla** [comment]
Not interested.

**Comment by neonnd** [comment]
> @BeepIsla
> 
> I just thought that it was possible to implement a **session killer** in CS:GO

session what

**Comment by uwutizm** [comment]
> 
> 
> > @BeepIsla
> > I just thought that it was possible to implement a **session killer** in CS:GO
> 
> session what

knowing the player's ip, you can prevent him from entering the servers. Any absolutely
